### ISSUE TITLE
Prices for the depot not 0?

### ISSUE THREAD

**Issue by azaryc2m** [bcamath-ds/OPLib#1]
Hi,
first of all, thanks for the collection. I'm currently using it to compare the results of my algorithm and test its validity. I've come up with an uncertainty - my solutions seem to be off by 1 for gen1, and i noticed that in the instance files published here the price for the depot is also set to 1. Now, normally depots have no price (so price of 0) and now i wonder if this was not mistaken when calculating the solutions. For lets say bier127-gen1-50.oplib, the solution has a node_count of 103, which includes the depot as far as i understand and also a score of 103, which with prices set to 1 must mean that the depo has also a price set to 1. Are my assumptions correct?

Edit: Normally i wouldn't ask since its heavily looking like the depots also have prices, but then there's "eil76-gen1-50.sol", for which the solution here is 46, but i get 47 (if i also include the 1 for depot), so it's not even consistent. I'm not 100% sure, my algorithm is working correctly so i can't rule that out, but something seems wrong (and yes, i'm rounding the distances exactly like in the description). So here's my solution for eil76-gen1-50_sol.json:

"Found a solution with 47 nodes, score 47 and route_cost 269: [0 72 32 62 15 2 43 31 8 38 71 57 11 39 16 50 5 67 74 75 66 6 34 7 45 33 51 26 44 28 47 4 36 19 69 59 70 35 46 20 73 27 61 21 41 40 42]" - bear in mind, that this list is 0-indexed.

**Comment by gkobeaga** [comment]
All the depots have non-zero scores in OPLib. These are benchmark instances of the literature, they were proposed in [Solving the Orienteering Problem through Branch-and-Cut](https://pubsonline.informs.org/doi/abs/10.1287/ijoc.10.2.133) (1998) by M. Fischetti, J. J. Salazar-González, P. Toth. There is no problem if you set a score of 0 to the depot (or just subtract the score of the depot to the solution).

The optimal solution of `eil76-gen1-50` has a score of 47.  However, the best solution obtained by the EA4OP algorithm (the one in the `solutions` directory) had 46. Does this clarify your question? You can check the optimal solution values at https://arxiv.org/abs/2011.02743.

**Comment by azaryc2m** [comment]
Yes, all my questions -and even more- have been answered, thank you very much :)
